### ISSUE TITLE
"continueTimerWhileOffline" not working in fabric 1.21.4, instantly revives anyone who logs out instead

### ISSUE THREAD

**Issue by PinguinKeks** [blay09/HardcoreRevival#160]
### Minecraft Version

Other (specify below)

### Mod Loader

Fabric

### Describe the Issue

If "continueTimerWhileOffline" is set to true, reconnecting simply revives the player

Config:

```toml
# Set to false to remove the Accept your Fate button and force players to wait out the timer.
allowAcceptingFate = false

# If true, knocked out players are still able to fire bows.
allowBows = false

# If true, knocked out players are still able to run commands. OPs are always able to run commands.
allowCommands = true

# If true, knocked out players are still able to fire pistols from Mr Crayfish's Gun Mod.
allowPistols = false

# If true, knocked out players are still able to punch nearby enemies.
allowUnarmedMelee = true

# The threshold of seconds that knockout will be treated as a consecutive knockout. See resumeTimerOnConsecutiveKnockout and multiplyTimerOnConsecutiveKnockout.
consecutiveKnockoutThresholdSeconds = 900

# If true, the timer until death continues even if the player logs out.
continueTimerWhileOffline = true

# If true, Hardcore Revival will not be active when playing alone in multiplayer.
disableInLonelyMultiplayer = false

# If true, Hardcore Revival will not be active in singleplayer.
disableInSingleplayer = false

# If true, knocked out players will glow, making them visible through blocks.
glowOnKnockout = false

# The damage sources that kill a player instantly, without a K.O. period.
instantDeathSources = [ "minecraft:lava","minecraft:lightning_bolt","minecraft:out_of_world","minecraft:outside_border","minecraft:wither","minecraft:generic_kill"]

# The multiplier to apply to the time remaining on consecutive knockouts.
multiplyTimerOnConsecutiveKnockout = 0.5

# The time in ticks it takes to rescue a player. 20 ticks are one second.
rescueActionTicks = 300

# The distance at which a player can rescue another.
rescueDistance = 1.5

# Effects applied to a player when rescued, in the format "effect|duration|amplifier"
rescueRespawnEffects = ["minecraft:weakness"|24000|4 ,"minecraft:slowness"|24000|5,"minecraft:mining_fatigue"|24000|4,"minecraft:blindness"|300|0]

# The food level to respawn with when a player was rescued, out of 20.
rescueRespawnFoodLevel = 5

# The amount of health to respawn with when a player was rescued, out of 20.
rescueRespawnHealth = 2

# If true, the timer until death resumes from its last time on consecutive knockouts.
resumeTimerOnConsecutiveKnockout = true

# The time in seconds in which a player can still be rescued from death. Set to 0 to disable the timer.
secondsUntilDeath = 900
```

### Logs

i don't have one atm sorry :c
